language: python
sudo: false
if: tag IS blank
services:
  - elasticsearch
cache:
  directories:
  - eggs
  - .npm
  - ~/.npm
  - node_modules
  - /home/travis/.cypress/Cypress
addons:
  apt:
    update: true
    packages:
    - bsdtar
    - build-essential
    - make
    - graphviz
    - nginx
  postgresql: '9.4'
env:
  global:
  - BOTO_CONFIG=/bogus
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - PATH="/usr/share/elasticsearch/bin:/usr/lib/postgresql/9.4/bin:$PATH"
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_COMMIT
  - USER="4dn-dcic"
  - SNO_REPO="snovault"
matrix:
  include:
  - python: '3.4'
    env: NPM=Test
  - python: '3.4'
    env: UNIT=Test
notifications:
  slack:
    secure: DQyUTk6evwPpO0P5+OPhBSgl+fGEerOjBlBwQliXAkDaMKH3Cpi4cTQ3ETR/+3g6bGqPGK+QJ1R+6Ht+hJD7dNomyVIoQmvF0P5afJtpk/A3cDILe90t76ET9jc/iBjWeUFQdokFUJ7Gt1GGYtI6e5XcVu/Qc/xqCvFMtsBN6mnBFuvcQki+WkoIIPPawyhfryCNOLo5vvbi4SZ5dZI+M0MGq9HQjOyF1sdIgKuXhxjupmL+kVPVXAq9kiOANYFkwbNsP9j0BTYW5wFHpAztBqz3NT6EchgCdue8tgV4hC4rRFvM/bsA4qz/TJ5wRRLBRXtnNtPcyhAqTiU+wC6qWt++fjSEMGe4KYqtRRV1YuxQiTVHN84t77DILLNfMh/6uSs0KijwOT+Oazwd/UsN1zYOH93AM4FZ0h92yyb6j6JQ+DUk4WFel1Zr4kZzhtHSPGw+K4fxY0zIt1qpaDPXjtZHQ0+LwIIMtwMp5bBcwDn9d1ADnUhUAuuIN2hHaXrVy4vP2hIcd0LzezBqvc7JXimyd5yRgUeOCTrKGkAeSo8VA7XIj0ZmlpQRYKNTJP+gz4Y6C/RCxISnFDF/vcX+IsDdvreZXJMplE1Aqxf0uR6Zj8Sr8q+QWGKydv6ettlLZuqDuv0l/l/9qpzYfRqLSZcetGRVFHHcR9wuQiDyums=
before_install:
-
- python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
- SNO_PATH="snovault = git https://github.com/$USER/$SNO_REPO.git rev="
- SNO_BRANCH=$(grep "${SNO_PATH}" buildout.cfg | sed "s@$SNO_PATH@@")
- SNO_STATUS=$(curl -s "https://api.travis-ci.org/$USER/$SNO_REPO.svg?branch=$SNO_BRANCH"
  | grep pass)
- ! "if [ -z \"$SNO_STATUS\" ]; then\n    echo \"Snovault branch build for $SNO_BRANCH
  is failing; exiting build\"\n    travis_terminate\nelse\n    echo \"Snovault branch
  $SNO_BRANCH is okay with build status: $SNO_STATUS\"\nfi\n"
- echo $tibanna_deploy
- postgres --version
- initdb --version
- nvm install 10
- node --version
- npm config set python /usr/bin/python2.7
install:
# need to manually change the version of six used by Travis for some reason
- pip uninstall -y six
- pip install six==1.11.0
- pip install coveralls
- pip install codacy-coverage
- pip install -U zc.buildout setuptools
- buildout bootstrap
- bin/buildout || (echo "Retrying buildout" && bin/buildout )
- pip show pytest
- pip install pytest==2.9.1
- pip show pytest
script:
- if test -n "$NPM"; then npm test --passWithNoTests; fi
# setone is essentially all tests that are not indexing; change here for clarity
- if test -n "$NPM"; then bin/test -v -v --aws-auth -m "not performance and not indexing and working" --durations=10
  --cov src/encoded;
  fi
- if test -n "$UNIT"; then bin/test -v -v --aws-auth -m "not performance and indexing and working" --durations=10
  --cov src/encoded;
  fi
- if test -n "$CYPRESS"; then travis_wait 30 deploy/run_cypress_tests_on_travis.sh;
  fi
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
after_success:
- coveralls
- ! "if test -n \"$NPM\"; then \n   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js\n
  \  cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage\n   rm -rf ./coverage\nfi\n"
- if test -n "$UNIT"; then python-codacy-coverage -r coverage.xml; fi
- python deploy/travis_after_all.py https://api.travis-ci.org
- export $(cat .to_export_back) >> /dev/null
- echo $TRAVIS_COMMIT_MESSAGE
- MSG_NO_WHITESPACE="$(echo -e "${TRAVIS_COMMIT_MSG}" | tr -d '[:space:]')"
- echo $MSG_NO_WHITESPACE
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- echo $tibanna_deploy
- ! "if [ \"$BUILD_LEADER\" = \"YES\" ]; then\n  if [ \"$BUILD_AGGREGATE_STATUS\"
  = \"others_succeeded\" ]; then\n    if [ \"$TRAVIS_PULL_REQUEST\" = \"false\" ];
  then\n      echo \"cleanup build artifacts\"\n      rm elasticsearch-5.4.1.deb\n
  \     rm .to_export_back\n      rm versions.cfg\n      pip install awsebcli\n      bin/aws
  s3 cp --recursive s3://encoded-4dn-conf-prod/.aws /home/travis/.aws\n      git remote
  add origin-travis https://${GH_TOKEN}@github.com/4dn-dcic/fourfront.git\n      git
  config --global user.email \"travis@builder.com\"\n      git config --global user.name
  \"Travis\"\n      if [ \"$TRAVIS_BRANCH\" = \"master\" ]; then\n         git config
  --replace-all remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'\n         git
  fetch --no-tags\n         git checkout master\n         \n         if [ -n \"$tibanna_deploy\"
  ]; then\n            echo \"Job succeeded! PUBLISHING to ${tibanna_deploy} environment...\"\n
  \           eb use ${tibanna_deploy} --debug\n            python deploy/deploy_beanstalk.py\n
  \        fi\n      fi\n     fi\n   fi\n  fi\n"
after_failure:
- python deploy/travis_after_all.py https://api.travis-ci.org
- export $(cat .to_export_back) >> /dev/null
notification:
  slack:
    rooms:
      secure: YuLIoKULHxT7ZY9nKVme0pVELk1HBS/nPjYYu4Bs48lOgJVK2I/OyvV9HVx2g7raK6/s4T7wTXG0EmljcakmKY78wsSyhR79fAZcV7+p4SobEi7nGHuHXVq0sp21ZeYiFJvD/5ospHX0hMudSicaANT66X7EyLTMdG/NGu5it6TPjcJWhxERXXz6Zbizm6j/wv2a64R0mMUGFSe1aWrFZv5ft+GgfupM2TPwX0PxNl2DamaGowJriKuU+svqIP7LXGuzYBxf9sj08gf3/S0e1r2bzg/ik4clzM2Lp5mcU27nLWh6TUr3hthFNsaKAFwIPS6Ay1Z8GeotAiZC538fyeM1zDvjz0Uu5fEuZnI89NVZ734NZfoFCEg4JcPDs8RHgzreR209zRgCVUh8AI7m7vMv302MNAjbG42FPlB1gDg9bukxbyytccm5/TuzAGLktG1jCWJk0uU34JsWZakF9fSqmFckppXZ1472cPQT+ityuszyUGEMgLvNxpZDpwMhywN7eMuQu64YD4ex1EvbidNEIdb0Z5UnpXaC2H+vxdBb+Qg58r/HN/S6OW8H+C/pZMuRMdm1AcgOjS9hROcRKgmwSD53Z/XXrT4GYZTW48jNOCFE2O+6RXUGqvQzcH8JG5blnTxoCV8dtb9GDbORQm7b80MOiidG8Xi8Jyq8oPM=
