dist: trusty
language: python
sudo: true
python:
  - "3.6"
if: tag IS blank
cache:
  directories:
  - eggs
  - .npm
  - ~/.npm
  - node_modules
  - /home/travis/.cypress/Cypress
addons:
  apt:
    packages:
    - bsdtar
    - build-essential
    - make
    - graphviz
    - nginx
  postgresql: '11.1'
env:
  global:
  - BOTO_CONFIG=/bogus
  - PATH="/usr/share/elasticsearch/bin:/usr/lib/postgresql/9.4/bin:$PATH"
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_COMMIT
  - USER="4dn-dcic"
  - SNO_REPO="snovault"
before_install:
- python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
- echo $tibanna_deploy
- postgres --version
- initdb --version
- nvm install 10 || (echo "Retrying nvm install" && sleep 5 && nvm install 10)
- node --version
- npm config set python /usr/bin/python2.7
install:
# need to manually change the version of six used by Travis for some reason
- pip uninstall -y six
- pip install six==1.11.0
- pip install --upgrade pip==19.0.3
- pip install poetry
- pip install coveralls
- pip install codacy-coverage
- poetry install
- make npm-setup
before_script:
- configure-kibana-index --es-endpoint search-fourfront-builds-uhevxdzfcv7mkm5pj5svcri3aq.us-east-1.es.amazonaws.com:80
script:
# setone is essentially all tests that are not indexing; change here for clarity
- travis_wait 30 bin/test --timeout=200 -v -v --aws-auth -m "working" --durations=10
  --cov src/encoded --es search-fourfront-builds-uhevxdzfcv7mkm5pj5svcri3aq.us-east-1.es.amazonaws.com:80;
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
- wipe-test-indices $TRAVIS_JOB_ID search-fourfront-builds-uhevxdzfcv7mkm5pj5svcri3aq.us-east-1.es.amazonaws.com:80
after_success:
- coveralls
- ! "if test -n \"$NPM\"; then \n   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js\n
  \  cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage\n   rm -rf ./coverage\nfi\n"
- if test -n "$UNIT"; then python-codacy-coverage -r coverage.xml; fi
- python deploy/travis_after_all.py https://api.travis-ci.org
- export $(cat .to_export_back) >> /dev/null
- echo $TRAVIS_COMMIT_MESSAGE
- MSG_NO_WHITESPACE="$(echo -e "${TRAVIS_COMMIT_MSG}" | tr -d '[:space:]')"
- echo $MSG_NO_WHITESPACE
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- echo $tibanna_deploy
- |
  if  [[ $TRAVIS_BRANCH == 'master' ]]; then
    echo 'Triggering docs build';
    curl -X POST -d "branches=master" -d "token=$DOCS_TOKEN" https://readthedocs.org/api/v2/webhook/cgap-portal/100087/;
  fi
after_failure:
- python deploy/travis_after_all.py https://api.travis-ci.org
- export $(cat .to_export_back) >> /dev/null
