#!/bin/bash -f

aws_account=
env_name=
do_login=
do_help=
creds_file=$HOME/.aws_test/test_creds.sh

if [ -f "${creds_file}" ]; then
  # Default the values of these variables by peeking in the test_creds.sh script
  aws_account=`grep 'export ACCOUNT_NUMBER=' ${creds_file} | sed -E 's|^export ACCOUNT_NUMBER=(.*)$|\1|'`
  env_name=`grep 'export ENV_NAME=' ${creds_file} | sed -E 's|^export ENV_NAME=(.*)$|\1|'`
fi

while [ $# -gt 0 ]; do
  if [ "$1" = "--aws_account" ]; then
    aws_account=$2
    shift 2
  elif [ "$1" = "--env_name" ]; then
    env_name=$2
    shift 2
  elif [ "$1" = "--login" ]; then
    do_login=TRUE
    shift 1
  elif [ "$1" = "--help" ]; then
    do_help=TRUE
    shift 1
  else
    do_help=TRUE
    break
  fi
done

if [ -n "${do_help}" ]; then
  echo "Syntax: $0 { --aws_account <account> | --env_name <env> | --login | --help }"
  echo ""
  echo " This will execute 'make build-docker-production AWS_ACCOUNT=<account> ENV_NAME=<env>'."
  echo " If --login is given, 'make ecr-login AWS_ACCOUNT=<account>' will be done first."
  echo " If unspecified, <account> defaults to '${aws_account}' (from 'export ACCOUNT_NUMBER=...' in ${creds_file})."
  echo " If unspecified, <env> defaults to '${env_name}' (from 'export ENV_NAME=...' in ${creds_file}.)"
  if [ ! -f "${creds_file}" ]; then
    echo " NOTE: The file ${creds_file} does not exist."
  fi
  echo ""
  exit 1
fi

if [ -z "${aws_account}" ]; then
  echo "--aws_account was not given to $0 and could not be found in ~/.aws_test/test_creds.sh"
  exit 1
fi

if [ -z "${env_name}" ]; then
  echo "--env_name was not given to $0 and could not be found in ~/.aws_test/test_creds.sh."
  exit 1
fi

if [ -n "${do_login}" ]; then
    make ecr-login AWS_ACCOUNT="${aws_account}"
fi
make build-docker-production AWS_ACCOUNT="${aws_account}" ENV_NAME="${env_name}"
