import os

APPLICATION_NAME = "cgap-portal"
APPLICATION_PYPROJECT_NAME = os.environ.get("APPLICATION_PYPROJECT_NAME") or "encoded"
os.environ["APPLICATION_PYPROJECT_NAME"] = APPLICATION_PYPROJECT_NAME
